services:
  postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql-dump.sql:/tmp/postgresql-dump.sql
    command: >
      sh -c "
      docker-entrypoint.sh postgres &
      sleep 1 &&
      psql -U postgres -d postgres -f /tmp/postgresql-dump.sql;
      wait
      "

  node-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - JOIN=query
    ports:
      - 3000:3000
    depends_on:
      - postgres
    profiles:
      - node

  deno-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: deno
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - JOIN=query
    ports:
      - 3000:3000
    depends_on:
      - postgres
    profiles:
      - deno

  bun-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: bun
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - JOIN=query
    ports:
      - 3000:3000
    depends_on:
      - postgres
    profiles:
      - bun

volumes:
  postgres-data:
